name = "TestRegistry"
uuid = "ef5aafdd-1b1f-4b9f-b60d-9a0b930606ac"
repo = "git@github.com:sjkelly/TestRegistry.jl.git"
description = "My private registry"

[packages]
e6723b4c-ebff-59f1-b4b7-d97aa5274f73 = { name = "Meshing", path = "M/Meshing" }
